-- 코드를 입력하세요
SELECT CART_ID
FROM (SELECT DISTINCT CART_ID
     FROM CART_PRODUCTS
     WHERE NAME = 'Milk'
     UNION ALL
     SELECT DISTINCT CART_ID
     FROM CART_PRODUCTS
     WHERE NAME = 'Yogurt') AS A
GROUP BY CART_ID
HAVING COUNT(CART_ID)=2
ORDER BY CART_ID
