-- 코드를 입력하세요
SELECT RE.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RE.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW AS RE
JOIN (SELECT *
     FROM REST_INFO
     WHERE ADDRESS LIKE '서울%') AS RI
ON RE.REST_ID = RI.REST_ID
GROUP BY RE.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC