-- 코드를 입력하세요
SELECT DR.APNT_NO, P.PT_NAME, DR.PT_NO, DR.MCDP_CD, DR.DR_NAME, DR.APNT_YMD
FROM PATIENT AS P
JOIN(SELECT A.APNT_NO, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_CNCL_YN, A.APNT_YMD
    FROM APPOINTMENT AS A
    JOIN DOCTOR AS D
    ON A.MDDR_ID = D.DR_ID
    ) AS DR
ON P.PT_NO = DR.PT_NO
WHERE DR.APNT_YMD LIKE '2022-04-13%' AND
    DR.APNT_CNCL_YN = 'N' AND
    DR.MCDP_CD = 'CS'
ORDER BY APNT_YMD
